// Client-side document generation — opens a print-ready window the user can
// "Save as PDF" or print. No backend / no PDF library required.

import { formatIDR } from "@/lib/currency";
import { totalOf, paidOf, balanceOf, isFullyPaid, paymentProgress, amountForPercent } from "@/lib/payments";
import moment from "moment";

const esc = (v) => String(v == null ? "" : v).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const fmt = (d, f = "MMM D, YYYY") => (d ? moment(d).format(f) : "—");

const STYLE = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #0B1B3B; margin: 0; padding: 40px; background: #fff; }
  .wrap { max-width: 720px; margin: 0 auto; }
  .head { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #AD1F23; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { font-size: 26px; font-weight: 800; letter-spacing: 1px; }
  .brand small { display: block; font-size: 11px; font-weight: 600; color: #5A6B85; letter-spacing: 3px; }
  .doc { text-align: right; }
  .doc .t { font-size: 13px; text-transform: uppercase; letter-spacing: 2px; color: #5A6B85; }
  .doc .c { font-size: 18px; font-weight: 700; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .muted { color: #5A6B85; font-size: 13px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px 28px; margin: 24px 0; }
  .row .k { font-size: 10px; text-transform: uppercase; letter-spacing: 1.5px; color: #5A6B85; }
  .row .v { font-size: 15px; font-weight: 600; margin-top: 2px; }
  .total { background: #0B1B3B; color: #fff; border-radius: 14px; padding: 16px 20px; display: flex; align-items: center; justify-content: space-between; margin-top: 20px; }
  .total .v { font-size: 22px; font-weight: 800; color: #fff; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 14px; }
  th, td { text-align: left; padding: 9px 8px; border-bottom: 1px solid #e7ebf2; }
  th { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #5A6B85; }
  .pill { display: inline-block; font-size: 11px; padding: 2px 10px; border-radius: 999px; background: #f0e7d6; color: #AD1F23; text-transform: capitalize; }
  .foot { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e7ebf2; font-size: 11px; color: #5A6B85; }
  @media print { body { padding: 0; } .noprint { display: none; } }
`;

export function printDocument(title, bodyHTML) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>${STYLE}</style></head><body><div class="wrap">${bodyHTML}<div class="foot">Icon Holiday Travel · This document was generated by the Icon Holiday platform. For assistance contact your travel concierge.</div></div></body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => { try { w.print(); } catch { /* user can print manually */ } }, 350);
}

function header(docLabel, code) {
  return `<div class="head">
    <div class="brand">Icon Holiday<small>TRAVEL</small></div>
    <div class="doc"><div class="t">${esc(docLabel)}</div><div class="c">${esc(code || "—")}</div></div>
  </div>`;
}

const row = (k, v) => `<div class="row"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`;

export function bookingVoucherHTML(b, opts = {}) {
  const code = b.confirmation_code || `ICH-${String(b.id || "").slice(-6).toUpperCase()}`;
  return `${header("Booking Voucher", code)}
    <h1>${esc(b.title || "Booking")}</h1>
    <p class="muted"><span class="pill">${esc(b.type || "booking")}</span> &nbsp; ${esc(b.status || "")}</p>
    <div class="grid">
      ${row("Provider", b.provider || "—")}
      ${opts.supplierName ? row("Supplier", opts.supplierName) : row("Guests", b.guests ?? "—")}
      ${row("Location", b.location || "—")}
      ${row("Confirmation", code)}
      ${row("Check-in", fmt(b.check_in))}
      ${row("Check-out", fmt(b.check_out))}
      ${opts.customerName ? row("Customer", opts.customerName) : ""}
      ${b.notes ? row("Notes", b.notes) : ""}
    </div>
    <div class="total"><span>Total paid</span><span class="v">${formatIDR(b.price || 0)}</span></div>`;
}

export function tripItineraryHTML(trip, items = [], members = []) {
  const sorted = [...items].sort((a, b) => (a.day_number ?? 0) - (b.day_number ?? 0) || String(a.time || "").localeCompare(String(b.time || "")));
  const days = sorted.reduce((acc, it) => { (acc[it.day_number ?? 1] = acc[it.day_number ?? 1] || []).push(it); return acc; }, {});
  const dayKeys = Object.keys(days).sort((a, b) => Number(a) - Number(b));
  const itinerary = dayKeys.length
    ? dayKeys.map((d) => `<h3 style="margin:18px 0 4px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#AD1F23">Day ${esc(d)}</h3>
        <table><tbody>${days[d].map((it) => `<tr><td style="width:70px;color:#AD1F23;font-weight:600">${esc(it.time || "")}</td><td><strong>${esc(it.activity_name || "Activity")}</strong>${it.location ? `<br><span class="muted">${esc(it.location)}</span>` : ""}</td><td style="text-align:right">${it.budget ? formatIDR(it.budget) : ""}</td></tr>`).join("")}</tbody></table>`).join("")
    : `<p class="muted">No activities planned yet.</p>`;
  const roster = members.length
    ? `<h3 style="margin:22px 0 4px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#AD1F23">Travelers</h3>
       <table><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody>${members.map((m) => `<tr><td>${esc(m.name)}</td><td style="text-transform:capitalize">${esc(m.role || "traveler")}</td><td style="text-transform:capitalize">${esc(m.status || "")}</td></tr>`).join("")}</tbody></table>`
    : "";
  const range = trip.start_date ? `${fmt(trip.start_date)}${trip.end_date ? ` – ${fmt(trip.end_date)}` : ""}` : "—";
  return `${header("Trip Itinerary", String(trip.id || "").slice(-6).toUpperCase())}
    <h1>${esc(trip.title || "Trip")}</h1>
    <p class="muted">${esc(trip.destination || "")} · ${esc(range)}</p>
    <div class="grid">
      ${row("Destination", trip.destination || "—")}
      ${row("Dates", range)}
      ${row("Travelers", members.length || trip.travelers || "—")}
      ${row("Budget", formatIDR(trip.budget_total || 0))}
    </div>
    ${itinerary}
    ${roster}`;
}

// Right-aligned money summary. Values are formatIDR output — no HTML-significant
// characters can reach it — so only the label needs escaping.
const sumRow = (k, v) =>
  `<tr><td style="border:0;padding:5px 8px;color:#5A6B85">${esc(k)}</td><td style="border:0;padding:5px 8px;text-align:right;font-weight:600">${v}</td></tr>`;

const sums = (rows) =>
  `<table style="width:auto;min-width:300px;margin-left:auto;page-break-inside:avoid"><tbody>${rows.filter(Boolean).join("")}</tbody></table>`;

// "cost_saver" → "cost saver", so the capitalizing .pill doesn't print the underscore.
const label = (v, fallback) => String(v || fallback).replace(/_/g, " ");

export function receiptHTML(booking, opts = {}) {
  const b = booking || {};
  const code = b.confirmation_code || `ICH-${String(b.id || "").slice(-6).toUpperCase()}`;
  const total = totalOf(b);
  const paid = paidOf(b);
  const balance = balanceOf(b);
  const settled = isFullyPaid(b);
  const pax = Math.max(1, Number(b.guests) || 1);
  const onDeposit = b.payment_plan === "dp";
  // The agreed deposit is what the customer signed up to; with none recorded,
  // how far the payment actually got is the honest stand-in.
  const dpPercent = Number(b.dp_percent) > 0 ? Math.round(Number(b.dp_percent)) : Math.round(paymentProgress(b) * 100);
  const sub = [b.provider, b.location].filter(Boolean).join(" · ");

  const note = settled
    ? `Received with thanks — no further payment is due.${onDeposit ? ` Settled in full after a ${dpPercent}% deposit.` : ""}`
    : `${onDeposit ? `This booking is on a ${dpPercent}% deposit plan. ` : ""}A balance of ${formatIDR(balance)} remains outstanding${b.balance_due_date ? ` and is due by ${fmt(b.balance_due_date)}` : ""}.`;

  return `${header("Receipt / Kwitansi", `RCP-${code}`)}
    <h1>${esc(b.title || "Booking")}</h1>
    <p class="muted"><span class="pill">${esc(label(b.type, "booking"))}</span> &nbsp; ${esc(b.status || "")}</p>
    <div class="grid">
      ${row("Receipt no", `RCP-${code}`)}
      ${row("Issue date", fmt(opts.issuedAt || b.updated_at || b.created_at))}
      ${row("Billed to", opts.customerName || b.customer_name || "—")}
      ${row("Email", opts.customerEmail || b.customer_email || "—")}
      ${row("Booking ref", code)}
      ${row("Payment plan", onDeposit ? `Deposit ${dpPercent}%` : "Full payment")}
    </div>
    <table>
      <thead><tr><th>Description</th><th style="text-align:center">Qty / Guests</th><th style="text-align:right">Unit price</th><th style="text-align:right">Amount</th></tr></thead>
      <tbody><tr>
        <td><strong>${esc(b.title || "Booking")}</strong>${sub ? `<br><span class="muted">${esc(sub)}</span>` : ""}</td>
        <td style="text-align:center">${pax}</td>
        <td style="text-align:right">${formatIDR(Math.round(total / pax))}</td>
        <td style="text-align:right">${formatIDR(total)}</td>
      </tr></tbody>
    </table>
    ${sums([
      sumRow("Total", formatIDR(total)),
      sumRow("Paid / Dibayar", formatIDR(paid)),
      sumRow("Balance due / Sisa tagihan", formatIDR(balance)),
    ])}
    <div class="total" style="page-break-inside:avoid">
      <span>${settled ? "Paid in full / Lunas" : "Balance due / Sisa tagihan"}</span>
      <span class="v">${formatIDR(settled ? total : balance)}</span>
    </div>
    <p class="muted" style="margin-top:10px">${esc(note)}</p>`;
}

export function quotationHTML(payload, opts = {}) {
  const p = payload || {};
  // Accepts a package, a booking-like record, or a { package, pax } wrapper.
  const q = p.package || p.pkg || p;
  const pax = Math.max(1, Number(opts.pax ?? p.pax ?? q.pax ?? q.guests ?? q.travelers) || 1);
  // Packages are quoted per person, but a booking's price is already the whole
  // party — multiplying the wrong one would double-charge the quote.
  const perPerson = opts.perPerson ?? !(q.guests != null || q.confirmation_code != null || q.payment_status != null);

  const price = Number(q.price) > 0 ? Number(q.price) : 0;
  const unit = perPerson ? price : Math.round(price / pax);
  const net = perPerson ? price * pax : price;
  const before = Number(q.price_before) > 0 ? Number(q.price_before) : 0;
  const listUnit = before > unit ? before : unit;
  const listTotal = before > unit ? before * pax : net;
  const discount = Math.max(0, listTotal - net) + Math.max(0, Number(opts.discount) || 0);
  const total = Math.max(0, listTotal - discount);

  // Numbered off the record being quoted so a reprint keeps the same reference.
  // Package ids are slugs, so normalise rather than truncate — a tail slice of
  // "pkg_maldives_signature" would number the quote "QT-NATURE".
  const quoteNo = opts.quoteNo || `QT-${String(q.confirmation_code || q.id || "").toUpperCase().replace(/[^A-Z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "DRAFT"}`;
  const issued = opts.issuedAt || new Date();
  const validDays = Number(opts.validDays) > 0 ? Number(opts.validDays) : 14;
  const validUntil = opts.validUntil || q.valid_until || moment(issued).add(validDays, "days");
  const departure = opts.departureDate || q.check_in || (Array.isArray(q.departure_dates) ? q.departure_dates[0] : null);

  // Mirrors the checkout's default when a package sets no minimum of its own.
  const rawDp = Number(opts.minDpPercent ?? q.min_dp_percent);
  const minDp = rawDp > 0 && rawDp <= 100 ? Math.round(rawDp) : 30;
  const dpAmount = amountForPercent(total, minDp);
  const onBalance = Math.max(0, total - dpAmount);
  const balanceDue = opts.balanceDueDate || (departure ? moment(departure).subtract(14, "days") : null);

  const terms = minDp >= 100
    ? `Full payment of ${formatIDR(total)} is due on confirmation.`
    : `A down payment of ${minDp}% — ${formatIDR(dpAmount)} — is due on confirmation to hold your places. The remaining ${formatIDR(onBalance)} is due ${balanceDue ? `by ${fmt(balanceDue)}` : "no later than 14 days before departure"}.`;

  const meta = [
    q.destination || q.location,
    q.duration_days ? `${q.duration_days} days${q.duration_nights ? ` / ${q.duration_nights} nights` : ""}` : "",
  ].filter(Boolean).join(" · ");

  return `${header("Quotation / Penawaran", quoteNo)}
    <h1>${esc(q.title || "Travel quotation")}</h1>
    <p class="muted"><span class="pill">${esc(label(q.category || q.type, "package"))}</span> &nbsp; ${esc(meta)}</p>
    <div class="grid">
      ${row("Quote no", quoteNo)}
      ${row("Issue date", fmt(issued))}
      ${row("Valid until", fmt(validUntil))}
      ${row("Travellers", `${pax} pax`)}
      ${departure ? row("Departure", fmt(departure)) : ""}
      ${row("Prepared for", opts.customerName || q.customer_name || "—")}
      ${row("Email", opts.customerEmail || q.customer_email || "—")}
      ${opts.customerPhone ? row("Phone", opts.customerPhone) : ""}
    </div>
    <table>
      <thead><tr><th>Description</th><th style="text-align:center">Pax</th><th style="text-align:right">Price / pax</th><th style="text-align:right">Amount</th></tr></thead>
      <tbody><tr>
        <td><strong>${esc(q.title || "Travel package")}</strong>${meta ? `<br><span class="muted">${esc(meta)}</span>` : ""}</td>
        <td style="text-align:center">${pax}</td>
        <td style="text-align:right">${formatIDR(listUnit)}</td>
        <td style="text-align:right">${formatIDR(listTotal)}</td>
      </tr></tbody>
    </table>
    ${sums([
      sumRow("Subtotal", formatIDR(listTotal)),
      discount > 0 ? sumRow("Discount / Diskon", `-${formatIDR(discount)}`) : "",
    ])}
    <div class="total" style="page-break-inside:avoid">
      <span>Grand total / Total</span>
      <span class="v">${formatIDR(total)}</span>
    </div>
    <div style="page-break-inside:avoid">
      <h3 style="margin:22px 0 4px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#AD1F23">Payment terms / Ketentuan pembayaran</h3>
      <p style="margin:0;font-size:13px">${esc(terms)}</p>
      <p class="muted" style="margin:6px 0 0">${esc(`This quotation is valid until ${fmt(validUntil)}. Prices and availability are confirmed once the down payment is received.`)}</p>
    </div>`;
}
