// Client-side document generation — opens a print-ready window the user can
// "Save as PDF" or print. No backend / no PDF library required.

import { formatIDR } from "@/lib/currency";
import moment from "moment";

const esc = (v) => String(v == null ? "" : v).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const fmt = (d, f = "MMM D, YYYY") => (d ? moment(d).format(f) : "—");

const STYLE = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #0B1B3B; margin: 0; padding: 40px; background: #fff; }
  .wrap { max-width: 720px; margin: 0 auto; }
  .head { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #AD1F23; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { font-size: 26px; font-weight: 800; letter-spacing: 1px; }
  .brand small { display: block; font-size: 11px; font-weight: 600; color: #5A6B85; letter-spacing: 3px; }
  .doc { text-align: right; }
  .doc .t { font-size: 13px; text-transform: uppercase; letter-spacing: 2px; color: #5A6B85; }
  .doc .c { font-size: 18px; font-weight: 700; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .muted { color: #5A6B85; font-size: 13px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px 28px; margin: 24px 0; }
  .row .k { font-size: 10px; text-transform: uppercase; letter-spacing: 1.5px; color: #5A6B85; }
  .row .v { font-size: 15px; font-weight: 600; margin-top: 2px; }
  .total { background: #0B1B3B; color: #fff; border-radius: 14px; padding: 16px 20px; display: flex; align-items: center; justify-content: space-between; margin-top: 20px; }
  .total .v { font-size: 22px; font-weight: 800; color: #fff; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 14px; }
  th, td { text-align: left; padding: 9px 8px; border-bottom: 1px solid #e7ebf2; }
  th { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #5A6B85; }
  .pill { display: inline-block; font-size: 11px; padding: 2px 10px; border-radius: 999px; background: #f0e7d6; color: #AD1F23; text-transform: capitalize; }
  .foot { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e7ebf2; font-size: 11px; color: #5A6B85; }
  @media print { body { padding: 0; } .noprint { display: none; } }
`;

export function printDocument(title, bodyHTML) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>${STYLE}</style></head><body><div class="wrap">${bodyHTML}<div class="foot">Icon Holiday Travel · This document was generated by the Icon Holiday platform. For assistance contact your travel concierge.</div></div></body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => { try { w.print(); } catch { /* user can print manually */ } }, 350);
}

function header(docLabel, code) {
  return `<div class="head">
    <div class="brand">Icon Holiday<small>TRAVEL</small></div>
    <div class="doc"><div class="t">${esc(docLabel)}</div><div class="c">${esc(code || "—")}</div></div>
  </div>`;
}

const row = (k, v) => `<div class="row"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`;

export function bookingVoucherHTML(b, opts = {}) {
  const code = b.confirmation_code || `Icon Holiday-${String(b.id || "").slice(-6).toUpperCase()}`;
  return `${header("Booking Voucher", code)}
    <h1>${esc(b.title || "Booking")}</h1>
    <p class="muted"><span class="pill">${esc(b.type || "booking")}</span> &nbsp; ${esc(b.status || "")}</p>
    <div class="grid">
      ${row("Provider", b.provider || "—")}
      ${opts.supplierName ? row("Supplier", opts.supplierName) : row("Guests", b.guests ?? "—")}
      ${row("Location", b.location || "—")}
      ${row("Confirmation", code)}
      ${row("Check-in", fmt(b.check_in))}
      ${row("Check-out", fmt(b.check_out))}
      ${opts.customerName ? row("Customer", opts.customerName) : ""}
      ${b.notes ? row("Notes", b.notes) : ""}
    </div>
    <div class="total"><span>Total paid</span><span class="v">${formatIDR(b.price || 0)}</span></div>`;
}

export function tripItineraryHTML(trip, items = [], members = []) {
  const sorted = [...items].sort((a, b) => (a.day_number ?? 0) - (b.day_number ?? 0) || String(a.time || "").localeCompare(String(b.time || "")));
  const days = sorted.reduce((acc, it) => { (acc[it.day_number ?? 1] = acc[it.day_number ?? 1] || []).push(it); return acc; }, {});
  const dayKeys = Object.keys(days).sort((a, b) => Number(a) - Number(b));
  const itinerary = dayKeys.length
    ? dayKeys.map((d) => `<h3 style="margin:18px 0 4px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#AD1F23">Day ${esc(d)}</h3>
        <table><tbody>${days[d].map((it) => `<tr><td style="width:70px;color:#AD1F23;font-weight:600">${esc(it.time || "")}</td><td><strong>${esc(it.activity_name || "Activity")}</strong>${it.location ? `<br><span class="muted">${esc(it.location)}</span>` : ""}</td><td style="text-align:right">${it.budget ? formatIDR(it.budget) : ""}</td></tr>`).join("")}</tbody></table>`).join("")
    : `<p class="muted">No activities planned yet.</p>`;
  const roster = members.length
    ? `<h3 style="margin:22px 0 4px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#AD1F23">Travelers</h3>
       <table><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody>${members.map((m) => `<tr><td>${esc(m.name)}</td><td style="text-transform:capitalize">${esc(m.role || "traveler")}</td><td style="text-transform:capitalize">${esc(m.status || "")}</td></tr>`).join("")}</tbody></table>`
    : "";
  const range = trip.start_date ? `${fmt(trip.start_date)}${trip.end_date ? ` – ${fmt(trip.end_date)}` : ""}` : "—";
  return `${header("Trip Itinerary", String(trip.id || "").slice(-6).toUpperCase())}
    <h1>${esc(trip.title || "Trip")}</h1>
    <p class="muted">${esc(trip.destination || "")} · ${esc(range)}</p>
    <div class="grid">
      ${row("Destination", trip.destination || "—")}
      ${row("Dates", range)}
      ${row("Travelers", members.length || trip.travelers || "—")}
      ${row("Budget", formatIDR(trip.budget_total || 0))}
    </div>
    ${itinerary}
    ${roster}`;
}
