/* ================================================================
   Icon Holiday — sumber konten landing page
   Semua halaman membaca dari sini. Tidak ada build step: cukup edit
   array di bawah, konten di seluruh situs ikut berubah.
   ================================================================ */

const U = (id, w = 900) => `https://images.unsplash.com/${id}?w=${w}&q=80`;

/* ── Paket tour ──────────────────────────────────────────────── */
window.TOURS = [
  {
    id: "korea-7d",
    country: "Korea Selatan", region: "Asia Timur",
    title: "7 Hari South Korea — Incheon, Nami Island & Mt. Seorak",
    dates: ["23 Okt 2026"], days: 7, nights: 6, price: 22500000, priceBefore: 25900000, seats: 6,
    img: U("photo-1538485399081-7191377e8241"),
    gallery: [U("photo-1538485399081-7191377e8241"), U("photo-1517154421773-0529f29ea451"), U("photo-1601621915196-2621bfb0c8b0")],
    summary: "Musim gugur di Korea: pulau Nami yang keemasan, Gunung Seorak, dan malam di Myeongdong.",
    highlights: ["Nami Island saat musim gugur", "Seoraksan National Park", "Gyeongbokgung & hanbok", "Belanja di Myeongdong"],
    includes: ["Tiket pesawat PP kelas ekonomi", "Hotel bintang 4 (6 malam)", "Makan sesuai program", "Tour leader berbahasa Indonesia", "Bus pariwisata & tiket masuk objek wisata"],
    excludes: ["Pengurusan visa Korea Selatan", "Asuransi perjalanan", "Pengeluaran pribadi & tipping"],
    itinerary: [
      { d: 1, t: "Jakarta — Incheon", x: "Berkumpul di bandara, penerbangan malam menuju Incheon." },
      { d: 2, t: "Incheon — Seoul", x: "Tiba pagi, kunjungi Gyeongbokgung dan Bukchon Hanok Village." },
      { d: 3, t: "Nami Island & Petite France", x: "Menyeberang ke Pulau Nami, lalu desa bergaya Prancis." },
      { d: 4, t: "Mt. Seorak", x: "Cable car ke Gwongeumseong dan kuil Sinheungsa." },
      { d: 5, t: "Everland", x: "Seharian di taman hiburan terbesar Korea." },
      { d: 6, t: "Seoul kota", x: "N Seoul Tower, Myeongdong, dan waktu bebas berbelanja." },
      { d: 7, t: "Incheon — Jakarta", x: "Transfer ke bandara dan penerbangan pulang." },
    ],
  },
  {
    id: "china-11d",
    country: "China", region: "Asia Timur",
    title: "11 Hari Chongqing + Gunung Avatar Zhangjiajie + Chengdu",
    dates: ["11 Sep 2026", "14 Sep 2026", "23 Okt 2026", "27 Okt 2026"], days: 11, nights: 10,
    price: 22500000, priceBefore: 26500000, seats: 4,
    img: U("photo-1508804185872-d7badad00f7d"),
    gallery: [U("photo-1508804185872-d7badad00f7d"), U("photo-1547981609-4b6bfe67ca0b"), U("photo-1545893835-abaa50cbe628")],
    summary: "Tebing Avatar di Zhangjiajie, panda raksasa di Chengdu, dan hotpot Chongqing.",
    highlights: ["Tianmen Mountain & Glass Skywalk", "Zhangjiajie National Forest Park", "Panda Research Base Chengdu", "Hongya Cave Chongqing"],
    includes: ["Tiket pesawat PP + domestik", "Hotel bintang 4–5 (10 malam)", "Makan sesuai program", "Tour leader & guide lokal", "Tiket masuk objek wisata"],
    excludes: ["Visa China", "Asuransi perjalanan", "Tipping guide & driver"],
    itinerary: [
      { d: 1, t: "Jakarta — Chongqing", x: "Penerbangan menuju Chongqing." },
      { d: 2, t: "Chongqing", x: "Hongya Cave dan pusat kota di tepi Sungai Yangtze." },
      { d: 3, t: "Chongqing — Zhangjiajie", x: "Kereta cepat menuju Zhangjiajie." },
      { d: 4, t: "Tianmen Mountain", x: "Cable car terpanjang dunia dan Glass Skywalk." },
      { d: 5, t: "Avatar Mountain", x: "Zhangjiajie National Forest Park & Bailong Elevator." },
      { d: 6, t: "Grand Canyon & Glass Bridge", x: "Jembatan kaca tertinggi di dunia." },
      { d: 7, t: "Fenghuang", x: "Kota kuno di tepi sungai, indah saat malam." },
      { d: 8, t: "Zhangjiajie — Chengdu", x: "Perjalanan menuju Chengdu." },
      { d: 9, t: "Panda Base", x: "Bertemu panda raksasa di pagi hari." },
      { d: 10, t: "Chengdu kota", x: "Jinli Street, Kuil Wuhou, dan kuliner Sichuan." },
      { d: 11, t: "Chengdu — Jakarta", x: "Penerbangan pulang." },
    ],
  },
  {
    id: "china-9d",
    country: "China", region: "Asia Timur",
    title: "9 Hari Changsha, Fenghuang, Furong, Zhangjiajie & Changde",
    dates: ["8 Sep 2026", "25 Okt 2026", "14 Nov 2026"], days: 9, nights: 8,
    price: 17500000, priceBefore: 19900000, seats: 9,
    img: U("photo-1547981609-4b6bfe67ca0b"),
    gallery: [U("photo-1547981609-4b6bfe67ca0b"), U("photo-1508804185872-d7badad00f7d")],
    summary: "Hunan lengkap: kota kuno Fenghuang, air terjun Furong, dan tebing Zhangjiajie.",
    highlights: ["Kota kuno Fenghuang", "Furong Ancient Town", "Zhangjiajie & Glass Bridge", "Changde Willow Street"],
    includes: ["Tiket pesawat PP", "Hotel bintang 4 (8 malam)", "Makan sesuai program", "Tour leader", "Tiket masuk objek wisata"],
    excludes: ["Visa China", "Asuransi perjalanan", "Pengeluaran pribadi"],
    itinerary: [
      { d: 1, t: "Jakarta — Changsha", x: "Penerbangan menuju ibu kota Hunan." },
      { d: 2, t: "Changsha — Fenghuang", x: "Menuju kota kuno di tepi Sungai Tuojiang." },
      { d: 3, t: "Fenghuang", x: "Menyusuri kota tua, perahu, dan lampion malam hari." },
      { d: 4, t: "Furong Ancient Town", x: "Kota di atas air terjun." },
      { d: 5, t: "Zhangjiajie", x: "National Forest Park." },
      { d: 6, t: "Tianmen Mountain", x: "Cable car & Skywalk." },
      { d: 7, t: "Changde", x: "Willow Street dan kuliner lokal." },
      { d: 8, t: "Changsha", x: "Orange Isle dan waktu bebas." },
      { d: 9, t: "Changsha — Jakarta", x: "Penerbangan pulang." },
    ],
  },
  {
    id: "nz-12d",
    country: "New Zealand", region: "Oseania",
    title: "12 Hari New Zealand North & South Island",
    dates: ["7 Nov 2026"], days: 12, nights: 11, price: null, seats: 8,
    img: U("photo-1507699622108-4be3abd695ad"),
    gallery: [U("photo-1507699622108-4be3abd695ad"), U("photo-1469854523086-cc02fe5d8800")],
    summary: "Dua pulau sekaligus: Hobbiton, Rotorua, Milford Sound, dan Queenstown.",
    highlights: ["Hobbiton Movie Set", "Geotermal Rotorua", "Milford Sound cruise", "Queenstown & Skyline Gondola"],
    includes: ["Tiket pesawat PP + domestik", "Hotel (11 malam)", "Makan sesuai program", "Tour leader", "Tiket masuk objek wisata"],
    excludes: ["Visa New Zealand & NZeTA", "Asuransi perjalanan", "Pengeluaran pribadi"],
    itinerary: [
      { d: 1, t: "Jakarta — Auckland", x: "Penerbangan menuju Auckland." },
      { d: 2, t: "Auckland", x: "Sky Tower dan pusat kota." },
      { d: 3, t: "Hobbiton & Rotorua", x: "Desa Hobbit dan pertunjukan budaya Maori." },
      { d: 4, t: "Rotorua", x: "Te Puia geyser dan kolam lumpur." },
      { d: 5, t: "Waitomo — Auckland", x: "Gua glowworm." },
      { d: 6, t: "Christchurch", x: "Terbang ke Pulau Selatan." },
      { d: 7, t: "Lake Tekapo", x: "Danau biru dan Church of the Good Shepherd." },
      { d: 8, t: "Queenstown", x: "Skyline Gondola dan Lake Wakatipu." },
      { d: 9, t: "Milford Sound", x: "Pelayaran fjord seharian." },
      { d: 10, t: "Queenstown", x: "Arrowtown dan waktu bebas." },
      { d: 11, t: "Queenstown — Auckland", x: "Penerbangan domestik." },
      { d: 12, t: "Auckland — Jakarta", x: "Penerbangan pulang." },
    ],
  },
  {
    id: "japan-8d",
    country: "Jepang", region: "Asia Timur",
    title: "8 Hari Japan Golden Route — Tokyo, Fuji, Kyoto & Osaka",
    dates: ["15 Mar 2026", "2 Apr 2026", "20 Okt 2026"], days: 8, nights: 7,
    price: 28900000, priceBefore: 32500000, seats: 12,
    img: U("photo-1493976040374-85c8e12f0c0e"),
    gallery: [U("photo-1493976040374-85c8e12f0c0e"), U("photo-1540959733332-eab4deabeeaf")],
    summary: "Rute klasik Jepang dengan shinkansen, dari Tokyo sampai Osaka.",
    highlights: ["Gunung Fuji 5th Station", "Shinkansen Tokyo–Kyoto", "Fushimi Inari & Kiyomizudera", "Dotonbori Osaka"],
    includes: ["Tiket pesawat PP", "Hotel bintang 4 (7 malam)", "Makan sesuai program", "Shinkansen", "Tour leader & tiket masuk"],
    excludes: ["Visa Jepang", "Asuransi perjalanan", "Pengeluaran pribadi"],
    itinerary: [
      { d: 1, t: "Jakarta — Tokyo", x: "Penerbangan malam." },
      { d: 2, t: "Tokyo", x: "Asakusa, Sensoji, dan Shibuya Crossing." },
      { d: 3, t: "Gunung Fuji", x: "5th Station, Oshino Hakkai, dan onsen." },
      { d: 4, t: "Tokyo — Kyoto", x: "Shinkansen menuju Kyoto." },
      { d: 5, t: "Kyoto", x: "Fushimi Inari, Kiyomizudera, Gion." },
      { d: 6, t: "Nara — Osaka", x: "Todaiji dan rusa Nara, lanjut Osaka." },
      { d: 7, t: "Osaka", x: "Osaka Castle dan Dotonbori." },
      { d: 8, t: "Osaka — Jakarta", x: "Penerbangan pulang." },
    ],
  },
  {
    id: "europe-12d",
    country: "Eropa Barat", region: "Benua Eropa",
    title: "12 Hari Eropa Barat — Belanda, Belgia, Prancis & Swiss",
    dates: ["18 Apr 2026", "12 Jun 2026", "5 Sep 2026"], days: 12, nights: 11,
    price: 42500000, priceBefore: 47000000, seats: 5,
    img: U("photo-1502602898657-3e91760cbb34"),
    gallery: [U("photo-1502602898657-3e91760cbb34"), U("photo-1499856871958-5b9627545d1a")],
    summary: "Empat negara dalam satu perjalanan, termasuk Jungfraujoch dan Menara Eiffel.",
    highlights: ["Jungfraujoch — Top of Europe", "Menara Eiffel & Seine", "Kincir angin Zaanse Schans", "Grand Place Brussels"],
    includes: ["Tiket pesawat PP", "Hotel bintang 4 (11 malam)", "Makan sesuai program", "Bus pariwisata", "Tour leader & tiket masuk"],
    excludes: ["Visa Schengen", "Asuransi perjalanan", "Tipping & pengeluaran pribadi"],
    itinerary: [
      { d: 1, t: "Jakarta — Amsterdam", x: "Penerbangan menuju Belanda." },
      { d: 2, t: "Amsterdam", x: "Kanal, Dam Square, dan Zaanse Schans." },
      { d: 3, t: "Volendam — Brussels", x: "Desa nelayan, lanjut ke Belgia." },
      { d: 4, t: "Brussels — Paris", x: "Grand Place & Atomium, lanjut Paris." },
      { d: 5, t: "Paris", x: "Menara Eiffel dan cruise Sungai Seine." },
      { d: 6, t: "Paris", x: "Louvre, Champs-Élysées, dan Galeries Lafayette." },
      { d: 7, t: "Dijon — Swiss", x: "Perjalanan menuju perbatasan Swiss." },
      { d: 8, t: "Jungfraujoch", x: "Kereta gunung ke Top of Europe." },
      { d: 9, t: "Lucerne", x: "Chapel Bridge dan Lion Monument." },
      { d: 10, t: "Zurich", x: "Bahnhofstrasse dan danau." },
      { d: 11, t: "Zurich — Jakarta", x: "Penerbangan pulang." },
      { d: 12, t: "Tiba di Jakarta", x: "Sampai di tanah air." },
    ],
  },
];

/* ── Destinasi ───────────────────────────────────────────────── */
window.DESTS = [
  { id: "jepang", name: "Jepang", region: "Asia Timur", img: U("photo-1493976040374-85c8e12f0c0e"),
    blurb: "Kuil tua, shinkansen, dan musim yang selalu punya wajah berbeda.",
    best: "Mar–Mei (sakura) & Okt–Nov (momiji)", visa: "Visa waiver untuk pemegang e-paspor", currency: "JPY" },
  { id: "korea", name: "Korea Selatan", region: "Asia Timur", img: U("photo-1517154421773-0529f29ea451"),
    blurb: "Seoul yang sibuk, pulau Nami yang tenang, dan gunung Seorak di musim gugur.",
    best: "Apr–Jun & Sep–Nov", visa: "Visa turis diperlukan", currency: "KRW" },
  { id: "china", name: "China", region: "Asia Timur", img: U("photo-1508804185872-d7badad00f7d"),
    blurb: "Dari tebing Zhangjiajie sampai panda Chengdu dan Tembok Besar.",
    best: "Mar–Mei & Sep–Nov", visa: "Visa turis / bebas visa transit", currency: "CNY" },
  { id: "eropa", name: "Eropa Barat", region: "Benua Eropa", img: U("photo-1502602898657-3e91760cbb34"),
    blurb: "Empat negara dalam satu perjalanan — kanal, katedral, dan Pegunungan Alpen.",
    best: "Apr–Jun & Sep–Okt", visa: "Visa Schengen", currency: "EUR / CHF" },
  { id: "turki", name: "Turki", region: "Asia Barat", img: U("photo-1541432901042-2d8bd64b4a9b"),
    blurb: "Balon udara Cappadocia, Hagia Sophia, dan Selat Bosphorus.",
    best: "Apr–Jun & Sep–Nov", visa: "e-Visa", currency: "TRY" },
  { id: "newzealand", name: "New Zealand", region: "Oseania", img: U("photo-1507699622108-4be3abd695ad"),
    blurb: "Hobbiton, fjord Milford Sound, dan danau biru Pulau Selatan.",
    best: "Des–Feb (musim panas)", visa: "Visa + NZeTA", currency: "NZD" },
  { id: "dubai", name: "Dubai", region: "Asia Barat", img: U("photo-1512453979798-5ea266f8880c"),
    blurb: "Burj Khalifa, safari gurun, dan belanja bebas pajak.",
    best: "Nov–Mar", visa: "Visa on arrival / e-Visa", currency: "AED" },
  { id: "australia", name: "Australia", region: "Oseania", img: U("photo-1506973035872-a4ec16b8e8d9"),
    blurb: "Sydney Opera House, Gold Coast, dan satwa khas Australia.",
    best: "Sep–Nov & Mar–Mei", visa: "Visa turis (subclass 600)", currency: "AUD" },
];

/* ── Layanan ─────────────────────────────────────────────────── */
window.SERVICES = [
  { id: "tour", icon: "i-map", tone: 1, name: "Paket Tour",
    short: "Grup maupun privat ke Asia, Eropa, Australia hingga Amerika.",
    long: "Kami merancang perjalanan grup dan privat lengkap dengan penerbangan, hotel, transportasi darat, tiket masuk objek wisata, dan tour leader berbahasa Indonesia. Rute disusun dengan tempo yang masuk akal — cukup waktu di setiap tempat, tidak sekadar mengejar daftar kunjungan.",
    points: ["Tour grup dengan keberangkatan terjadwal", "Tour privat sesuai tanggal dan minat Anda", "Tour leader & guide lokal berpengalaman", "Sudah termasuk hotel, transportasi dan tiket masuk"] },
  { id: "tiket", icon: "i-plane", tone: 2, name: "Tiket Pesawat",
    short: "Harga korporat untuk rute domestik dan internasional.",
    long: "Sebagai agen resmi, kami menerbitkan tiket domestik dan internasional dengan harga korporat. Kalau rencana berubah, tim kami membantu proses reschedule maupun refund sesuai ketentuan maskapai — tidak perlu antre sendiri.",
    points: ["Tiket domestik & internasional", "Harga korporat untuk rombongan", "Bantuan reschedule dan refund", "Penerbitan cepat, e-ticket langsung dikirim"] },
  { id: "visa", icon: "i-doc", tone: 3, name: "Pengurusan Visa",
    short: "Lebih dari 30 negara — dokumen dicek sebelum diajukan.",
    long: "Kami membantu pengurusan visa untuk lebih dari 30 negara: Schengen, Amerika Serikat, Inggris, Jepang, Korea, China, Australia dan lainnya. Berkas Anda kami periksa lebih dulu supaya risiko penolakan karena dokumen kurang bisa ditekan.",
    points: ["Konsultasi persyaratan sebelum mengajukan", "Pengecekan kelengkapan dokumen", "Pendampingan pengisian formulir", "Informasi jadwal & lokasi biometrik"] },
  { id: "hotel", icon: "i-bed", tone: 4, name: "Hotel",
    short: "Jaringan hotel dan resort di seluruh dunia.",
    long: "Reservasi hotel dari bintang tiga sampai properti mewah, di dalam maupun luar negeri. Kami bantu memilih lokasi yang benar-benar dekat dengan rencana perjalanan Anda, bukan sekadar yang paling murah.",
    points: ["Hotel domestik & internasional", "Pilihan lokasi sesuai itinerary", "Harga agen untuk pemesanan rombongan", "Konfirmasi voucher langsung"] },
  { id: "cruise", icon: "i-ship", tone: 5, name: "Cruise",
    short: "Ocean cruise dan river cruise bersama operator internasional.",
    long: "Pelayaran laut maupun sungai bersama operator internasional — dari cruise Asia Tenggara beberapa malam sampai river cruise di Eropa. Kami bantu memilih kabin, jalur pelayaran, dan mengurus dokumen yang diperlukan.",
    points: ["Ocean cruise & river cruise", "Bantuan memilih kabin dan rute", "Pengurusan dokumen pelayaran", "Paket kombinasi cruise + tour darat"] },
];

/* ── Visa: negara yang dilayani ──────────────────────────────── */
window.VISA_COUNTRIES = [
  { g: "Eropa (Schengen)", c: ["Austria", "Belanda", "Denmark", "Finlandia", "Jerman", "Hongaria", "Italia", "Kroasia", "Norwegia", "Perancis", "Portugal", "Republik Ceko", "Spanyol", "Swedia", "Swiss", "Yunani"] },
  { g: "Eropa (non-Schengen)", c: ["Inggris Raya", "Ukraina"] },
  { g: "Amerika", c: ["Amerika Serikat", "Kanada"] },
  { g: "Asia", c: ["China", "India", "Jepang (Waiver)", "Korea Selatan", "Korea Selatan Group", "Taiwan"] },
  { g: "Timur Tengah & Afrika", c: ["Arab Saudi", "Dubai / UAE", "Mesir", "Afrika Selatan"] },
  { g: "Oseania", c: ["Australia", "Selandia Baru"] },
];

/* ── Artikel ─────────────────────────────────────────────────── */
window.NEWS = [
  { id: "visa-global", tag: "Info Visa", date: "2 Juni 2026", img: U("photo-1488646953014-85cb44e25828"),
    title: "Layanan visa global untuk berbagai negara",
    sum: "Ringkasan syarat dan alur pengajuan visa untuk destinasi yang paling sering ditanyakan.",
    body: ["Setiap negara punya daftar dokumen dan alur yang berbeda, dan aturannya berubah lebih sering daripada yang orang kira. Yang paling umum diminta tetap sama: paspor berlaku minimal enam bulan, bukti keuangan, bukti pekerjaan atau usaha, serta rencana perjalanan yang jelas.",
      "Yang membuat pengajuan gagal biasanya bukan hal besar — melainkan rekening yang saldonya baru saja melonjak, itinerary yang tidak konsisten dengan tanggal tiket, atau formulir yang isinya berbeda dengan dokumen pendukung.",
      "Kami memeriksa berkas Anda sebelum diajukan, lalu mendampingi pengisian formulir dan penjadwalan biometrik bila diperlukan."] },
  { id: "etias", tag: "Aturan Baru", date: "22 Mei 2026", img: U("photo-1502602898657-3e91760cbb34"),
    title: "Sistem ETIAS Uni Eropa mulai berlaku akhir 2026",
    sum: "Apa yang berubah untuk pemegang paspor Indonesia yang bepergian ke kawasan Schengen.",
    body: ["ETIAS adalah sistem otorisasi perjalanan elektronik untuk kawasan Schengen. Sistem ini bukan pengganti visa — pemegang paspor yang tetap memerlukan visa Schengen harus tetap mengajukan visa seperti biasa.",
      "Yang perlu disiapkan tetap sama: paspor yang masih berlaku, rencana perjalanan, dan akomodasi. Kami akan memperbarui panduan ini begitu ketentuan finalnya diumumkan.",
      "Untuk perjalanan Eropa dalam waktu dekat, sebaiknya proses visa dimulai minimal 6–8 minggu sebelum keberangkatan."] },
  { id: "cruise-vs", tag: "Cruise", date: "30 April 2026", img: U("photo-1548574505-5e239809ee19"),
    title: "Ocean cruise atau river cruise — mana yang cocok?",
    sum: "Perbedaan rute, kapal dan suasana, supaya Anda tidak salah pilih untuk liburan pertama.",
    body: ["Ocean cruise memakai kapal besar dengan fasilitas lengkap — kolam renang, teater, banyak restoran — dan berlayar antar pulau atau antar negara. Cocok untuk keluarga besar dan mereka yang menikmati kapal itu sendiri sebagai bagian dari liburan.",
      "River cruise memakai kapal jauh lebih kecil, menyusuri sungai seperti Danube atau Rhine, dan berlabuh hampir setiap hari tepat di pusat kota. Cocok bila tujuan Anda adalah kotanya, bukan kapalnya.",
      "Pertimbangan praktis: ocean cruise umumnya lebih ekonomis per malam, sementara river cruise lebih santai dan tidak memerlukan transfer panjang dari pelabuhan ke kota."] },
  { id: "powerbank", tag: "Penerbangan", date: "8 April 2026", img: U("photo-1436491865332-7a61a109cc05"),
    title: "Aturan baru membawa power bank di pesawat",
    sum: "Beberapa maskapai memperketat ketentuan power bank di kabin — ini yang perlu disiapkan.",
    body: ["Power bank hanya boleh dibawa di kabin, tidak pernah di bagasi tercatat. Batas kapasitas yang umum berlaku adalah 100 Wh tanpa persetujuan khusus, dan 100–160 Wh dengan persetujuan maskapai.",
      "Sejumlah maskapai kini juga mensyaratkan label kapasitas yang terbaca jelas dan melarang penggunaan power bank selama penerbangan.",
      "Pastikan kapasitas tertera pada badan power bank. Unit tanpa label berisiko ditahan di pemeriksaan keamanan."] },
  { id: "koper-kabin", tag: "Tips", date: "9 April 2026", img: U("photo-1553531384-cc64ac80f931"),
    title: "Batas koper kabin di maskapai Indonesia",
    sum: "Ukuran dan berat yang berlaku, plus cara menghindari biaya tambahan di gate.",
    body: ["Sebagian besar maskapai Indonesia menetapkan batas 7 kg untuk bagasi kabin, dengan dimensi sekitar 56 x 36 x 23 cm. Beberapa maskapai berbiaya rendah menerapkan batas lebih ketat.",
      "Penimbangan di gate makin sering dilakukan. Barang berat seperti kamera dan laptop sebaiknya dimasukkan ke tas kecil yang dihitung sebagai personal item.",
      "Bila membawa oleh-oleh dalam jumlah banyak, membeli bagasi tambahan saat pemesanan hampir selalu lebih murah daripada membayar di bandara."] },
  { id: "china-transit", tag: "Info Visa", date: "25 Feb 2026", img: U("photo-1545893835-abaa50cbe628"),
    title: "Transit di China tanpa visa hingga 240 jam",
    sum: "Warga negara Indonesia bisa transit sampai 10 hari tanpa visa, asal rutenya sesuai.",
    body: ["Kebijakan bebas visa transit memungkinkan singgah hingga 240 jam di kota-kota tertentu, dengan syarat rute penerbangan menuju negara ketiga — bukan kembali ke negara asal.",
      "Tiket lanjutan dengan tanggal dan tujuan yang jelas wajib ditunjukkan saat tiba. Wilayah yang boleh dikunjungi juga dibatasi sesuai kota masuk.",
      "Kalau rencana Anda hanya singgah beberapa hari di Shanghai atau Beijing sebelum melanjutkan perjalanan, skema ini bisa menghemat biaya dan waktu pengurusan visa."] },
];

/* ── Galeri ──────────────────────────────────────────────────── */
window.GALLERY = [
  { img: U("photo-1538485399081-7191377e8241"), cap: "Grup Korea Selatan — Oktober 2025" },
  { img: U("photo-1508804185872-d7badad00f7d"), cap: "Zhangjiajie, China — September 2025" },
  { img: U("photo-1502602898657-3e91760cbb34"), cap: "Eropa Barat — Juni 2025" },
  { img: U("photo-1493976040374-85c8e12f0c0e"), cap: "Kyoto, Jepang — April 2025" },
  { img: U("photo-1507699622108-4be3abd695ad"), cap: "New Zealand — November 2024" },
  { img: U("photo-1541432901042-2d8bd64b4a9b"), cap: "Cappadocia, Turki — Mei 2025" },
  { img: U("photo-1512453979798-5ea266f8880c"), cap: "Dubai — Februari 2025" },
  { img: U("photo-1517154421773-0529f29ea451"), cap: "Seoul, Korea — Oktober 2025" },
  { img: U("photo-1547981609-4b6bfe67ca0b"), cap: "Fenghuang, China — September 2025" },
];

/* ── Testimoni ───────────────────────────────────────────────── */
window.REVIEWS = [
  { text: "Perencanaannya rapi dari awal. Semua pertanyaan kami dijawab cepat, dan selama di sana tour leader-nya sangat membantu.", who: "Lisna Z.", trip: "Tour Korea Selatan" },
  { text: "Pengurusan visa keluarga kami dibantu sampai detail dokumennya. Prosesnya jauh lebih tenang dibanding urus sendiri.", who: "Willy C.", trip: "Visa Schengen" },
  { text: "Harga tiketnya masuk akal dan tim-nya responsif waktu kami perlu ubah jadwal mendadak. Recommended.", who: "Darius O.", trip: "Tiket & Hotel" },
  { text: "Ini kali ketiga kami berangkat bersama Icon Holiday. Hotelnya selalu dekat dengan pusat kota, itu yang bikin kami balik lagi.", who: "Winarto A.", trip: "Tour Jepang" },
  { text: "Anak-anak senang, orang tua tidak kelelahan. Temponya pas untuk keluarga tiga generasi.", who: "Kurniawan L.", trip: "Tour China" },
  { text: "Dari konsultasi sampai pulang, satu tim yang sama yang menangani. Tidak perlu menjelaskan ulang ke orang berbeda.", who: "Fandy J.", trip: "Cruise Asia Tenggara" },
];

/* ── Profil perusahaan ───────────────────────────────────────── */
window.COMPANY = {
  offices: [
    { city: "Medan", legal: "PT. Inter Continent Indonesia", addr: "Jl. Brigjend Katamso, Komp. Istana Bisnis Centre No. 43, Medan", tel: "(061) 4520 888", telHref: "+62614520888" },
    { city: "Jakarta", legal: "PT. Icon Holiday Indonesia", addr: "Jl. Muara Karang Raya No. 185, Jakarta Utara, Jakarta", tel: "(021) 6660 8888", telHref: "+62216660888" },
  ],
  hours: ["Senin – Jumat  09.00 – 17.00", "Sabtu  09.00 – 14.00", "Minggu & hari libur — tutup"],
  social: { ig: "https://instagram.com/iconholidaymedan", fb: "https://www.facebook.com/iconholiday" },
  wa: "6281200000000", // TODO: ganti dengan nomor WhatsApp asli
};
